### ISSUE TITLE
List spacing not consistent

### ISSUE THREAD

**Issue by leo-paz** [data-maki/flowtoken#10]
Here are examples of markdown vs how they are displayed by `AnimatedText` when i run `npm run storybook`.
Markdown:
![image](https://github.com/user-attachments/assets/44f1918e-76d8-4076-9cfc-e6476c576ed6)
Displayed:
![image](https://github.com/user-attachments/assets/f4089946-015d-47b9-bf1d-45556c6f1741)

Odd extra spacing after the second element.

Here is where it gets really weird
Markdown:
![image](https://github.com/user-attachments/assets/db72e123-50a5-454e-8f3e-c0799cc8ca9e)
Displayed:
![image](https://github.com/user-attachments/assets/1adf346a-3d34-4064-85d1-acb6e02340d9)

You can see that spacing is handled really badly when there is a newline after each list item. My LLM spits out markdown like this sometimes and its just not reliable to try and tell it to not. 

I would expect behaviour similar to this:
![image](https://github.com/user-attachments/assets/b365aaba-96a6-4d19-a801-fce8cf6f402d)

**Comment by Ephibbs** [comment]
Merged!
