### ISSUE TITLE
Support Custom Markdown Components

### ISSUE THREAD

**Issue by leo-paz** [data-maki/flowtoken#3]
Super cool project! Works really well.

One feature request - It would be great if we could pass in our own markdown components. 

The best example that comes to mind is how perplexity reveals citation components as its streaming text.

**Comment by Ephibbs** [comment]
Happy to hear and that's a great idea!

So converting an html tag in markdown as a custom react component I suppose. Let me know if you have any other thoughts.

I'll work on a update for this in the next couple days!

**Comment by leo-paz** [comment]
@Ephibbs Yeah I would expect an API that lets me pass in a regex expression along with the react component that renders when that pattern is hit.

For example `const citationRegex = /\{\{([^}]+)\}\}/g` for matching `{{citationId}}` syntax in markdown.

One thing that is important is that the user never sees any piece of the custom markdown syntax so they would never see `{{` streamed first before it corrects itself to the proper react component. They only see the full component it was meant to be replaced with.

**Comment by Ephibbs** [comment]
The fix has been merged into the main branch, so this functionality is now live in 1.0.18! #4

**Comment by MarLapuz** [comment]
Hey @Ephibbs, 

This package is really impressive! I was wondering if it's possible to detect a specific regex match in the content, particularly for footnotes or citations typically formatted as `[^1]`, `[^2]`, etc. For example, in a string like:

```
Determining whether a stock is overvalued, undervalued, or fairly priced involves a combination of financial analysis and an understanding of market sentiment [^3] [^5]. Several key metrics and approaches can help you assess a stock's valuation, and it's important to consider a range of factors rather than relying on a single measure [^1].
```

Not sure how to pass it as a regex key on the object. 😅
