### ISSUE TITLE
word breaking

### ISSUE THREAD

**Issue by yemyat** [data-maki/flowtoken#9]
It seems like there's currently no APIs available to make sure that the words are not broken. 

Here's an example:
![CleanShot 2024-11-19 at 21 49 30@2x](https://github.com/user-attachments/assets/4e5d090d-a3e7-4085-ae44-0eb5e6fa7b24)

Would be great to have an option to make sure that letters don't break into a new line individually. I've tried using tailwind's whitespace-wrap options with a wrapper div but didn't work.

**Comment by Ephibbs** [comment]
You can avoid breaking on words by using `sep="word"`. 

When splitting on characters for the animation, that will happen. I haven't found a great way to prevent that yet.

**Comment by yemyat** [comment]
I'm actually using that `sep="word"`
![CleanShot 2024-11-20 at 07 17 50@2x](https://github.com/user-attachments/assets/15dbd9af-a3b4-4d31-9a66-d16fbff1c5a5)

**Comment by isaacwasserman** [comment]
Was a solution ever found for this problem? I'm experiencing something similar.

**Comment by harisrab** [comment]
This problem is happening again. I try using htmlComponents but it would flake out on animation.
